module.exports = {
  rosSidebar: [{type: 'autogenerated', dirName: 'ros'}],
  concretoArmadoSidebar: [{type: 'autogenerated', dirName: 'concreto-armado'}],
  eletricidadeSidebar: [{type: 'autogenerated', dirName: 'eletricidade'}],
};
